== ec2-deploy-actions

Use this action to deploy an Amazon Elastic Compute Cloud (Amazon EC2) binary. Amazon EC2 is a web service of Amazon Web Services (AWS).


== Inputs

[cols="2a,1a,1a,3a",options="header"]
.Input details
|===

| Input name
| Data type
| Required?
| Description

| `aws-host`
| String
| Yes
| The Amazon EC2 host URL.

| `aws-ssh-key-data`
| String
| Yes
| The AWS SSH key data.

| `aws-user`
| String
| Yes
| The AWS user to connect as.

| `source-location`
| String
| Yes
| The source location to copy files from.

| `destination-ec2-location`
| String
| Yes
| The destination location in the Amazon EC2 host.

| `deploy-command`
| String
| No
| The command to execute after deploying to the destination location.

| `deploy-script`
| String
| No
| The script file to execute after deploying to the destination location.
|===







 This action can be used to invoke the ec2 deploy and execute script specified at the destination.

```yaml
    - name: ec2-deploy-with-script
      uses: calculi-corp/ec2-deploy-actions@v1
      with:
        source-location: ${{ cloudbees.workspace }}/test/*
        destination-ec2-location: /home/ubuntu/mydeploys/hellowworld/
         aws-host: ${{ secrets.EC2-ACTION-DEPLOY-HOST }}
        aws-ssh-key-data: ${{ secrets.EC2-ACTION-DEPLOY-KEY }}
        aws-user: ubuntu
        deploy-script: script1.sh
``` 
